export const FETCH_DOGS = 'FETCH_DOGS';
export const FETCH_BREEDS_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_BREEDS_START = 'FETCH_START';

export const FETCH_IMAGE_START = 'FETCH_IMAGE_START';
export const FETCH_IMAGE_SUCCESS = 'FETCH_IMAGE_SUCCESS';
export const IMAGES_ARE_LOADED = 'IMAGES_ARE_LOADED';

export const DOG_IS_SELECTED = 'DOG_IS_SELECTED';

export const GET_DOGS_IMAGE_START = 'GET_DOGS_IMAGE_START';
export const GET_DOGS_IMAGE_SUCCESS = 'GET_DOGS_IMAGE_SUCCESS';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';